apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim
spec:
  accessModes:
    - ReadWriteOnce  # The PVC should match the access mode of the PV
  resources:
    requests:
      storage: 1Gi  # The requested size for the claim
